version: '3.8'

services:
  scheduler:
    user: root
    environment:
      PYTHONPATH: /usr/local/airflow
    volumes:
<<<<<<< HEAD
      - type: bind
        source: /media/lucas/Files/2.Projetos/0.mylake
        target: /usr/local/airflow/mylake
  webserver:
    volumes:
      - type: bind
        source: /media/lucas/Files/2.Projetos/0.mylake
        target: /usr/local/airflow/mylake
  triggerer:
    volumes:
      - type: bind
        source: /media/lucas/Files/2.Projetos/0.mylake
        target: /usr/local/airflow/mylake
=======
      - ./dbt/demodadosdw/:/usr/local/airflow/dbt/demodadosdw
      - ./include/local_setup/src:/usr/local/airflow/src
      - /media/lucas/Files/2.Projetos/0.mylake:/usr/local/airflow/mylake

>>>>>>> voltar-um
  dag-processor:
    user: root
    environment:
      PYTHONPATH: /usr/local/airflow
    volumes:
<<<<<<< HEAD
      - type: bind
        source: /media/lucas/Files/2.Projetos/0.mylake
        target: /usr/local/airflow/mylake
=======
      - ./dbt/demodadosdw/:/usr/local/airflow/dbt/demodadosdw
      - ./include/local_setup/src:/usr/local/airflow/src
      - /media/lucas/Files/2.Projetos/0.mylake:/usr/local/airflow/mylake
>>>>>>> voltar-um
